modLoader="javafml"
loaderVersion="[45,]"
issueTrackerURL="http://github.com/coolsimulations/survivalplus-lightsabers/issues/"
logoFile="cubed.png"
license="All rights reserved"

[modproperties.lightsaber]
    catalogueImageIcon="icon.png"

[[mods]]
    modId="lightsaber"
    version="0.1.7b"
    updateJSONURL="https://coolsimulations.net/mcmods/lightsaber/versionchecker.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/survivalplus-lightsabers"
    displayName="SurvivalPlus Lightsabers"
    credits="To leviofpower and Jessen_House who have both played a vital part in testing this mod throughout its development. Credit to Sushi_Witch for the amazing Lightsaber, Darksaber and Lightsaber Parts models! Also, credit goes to Star Wars and Lucasfilms for Lightsaber related concepts and assets."
    authors="coolsim"
    description='''
    This is an official add-on for SurvivalPlus that adds Lightsabers!
    '''
[[dependencies.lightsaber]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.9,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightsaber]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightsaber]]
    modId="survivalplus"
    mandatory=true
    versionRange="[0.1.7b,]"
    ordering="BEFORE"
    side="BOTH"